-- V002_2__Insert-data.sql


-- TODO: implement data loading from CSV files

-- <changeSet id="002 = Insert data into tables" author="konstantin">
--         <loadData
--                 file="./data/country.csv"
--                 relativeToChangelogFile="true"
--                 separator=","
--                 tableName="country"
--                 usePreparedStatements="true">
--             <column name="name" type="string"/>
--         </loadData>
--
--         <loadData
--                 file="./data/city.csv"
--                 relativeToChangelogFile="true"
--                 separator=","
--                 tableName="city"
--                 usePreparedStatements="true">
--             <column name="name" type="string"/>
--         </loadData>
--
--         <loadData
--                 file="./data/countrylanguage.csv"
--                 relativeToChangelogFile="true"
--                 separator=","
--                 tableName="countrylanguage"
--                 usePreparedStatements="true">
--             <column name="name" type="string"/>
--         </loadData>